declare module "react-helmet";
declare module "react-table";
declare module "faker";
declare module "react-tooltip";
declare module "react-simple-maps";
declare module "formik";
declare module "react-range-slider-input";
declare module "react-input-mask";
declare module "d3-geo";
